#!/usr/bin/env python

import json
from numbers import Number
import sys
from compiler.ast import flatten

def main():
    template = json.load(sys.stdin)

    (graph, edges) = extract_graph(template['Description'], template['Resources'])
    graph['edges'].extend(edges)
    handle_terminals(template, graph, 'Parameters', 'source')
    handle_terminals(template, graph, 'Outputs', 'sink')

    render(graph)

def handle_terminals(template, graph, name, rank):
    if name in template:
        (subgraph, edges) = extract_graph(name, template[name])
        subgraph['rank'] = rank
        graph['subgraphs'].append(subgraph)
        graph['edges'].extend(edges)

        # Use a down-pointing arrow type shape
        subgraph['shape'] = 'house'
        subgraph['orientation'] = '180.0'
        subgraph['style'] = 'filled'

def extract_graph(name, elem):
    graph = {'name': name, 'nodes': [], 'edges': [], 'subgraphs': []}
    edges = []
    for item, details in elem.iteritems():
        graph['nodes'].append({'name': item})
        edges.extend(flatten(find_refs(item, details)))
    return (graph, edges)

def find_refs(context, elem):
    if isinstance(elem, dict):
        refs = []
        for k, v in elem.iteritems():
            if unicode(k) == unicode('Ref'):
                assert isinstance(v, basestring), 'Expected a string: %s' % v
                refs.append({'from': v, 'to': context})
            elif unicode(k) == unicode('Fn::GetAtt'):
                assert isinstance(v, list), 'Expected a list: %s' % v
                refs.append({'from': v[0], 'to': context})
            else:
                refs.extend(find_refs(context, v))
        return refs
    elif isinstance(elem, list):
        return map(lambda e: find_refs(context, e), elem)
    elif isinstance(elem, basestring):
        return []
    elif isinstance(elem, bool):
        return []
    elif isinstance(elem, Number):
        return []
    else:
        raise AssertionError('Unexpected type: %s' % elem)

def render(graph, subgraph=False):
    if subgraph:
        prefix = '  '
    else:
        prefix = ''
    print '%s "%s" {' % ('subgraph' if subgraph else 'digraph', graph['name'])
    print '%slabeljust=l;' % prefix
    if 'shape' in graph:
        print '%snode [shape="%s"];' % (prefix, graph['shape'])
    else:
        print '%snode [shape="box"];' % prefix
    if 'style' in graph:
        print '%snode [style="%s"]' % (prefix, graph['style'])
    if 'rank' in graph:
        print '%srank=%s' % (prefix, graph['rank'])
    for n in graph['nodes']:
        print '%s"%s"' % (prefix, n['name'])
    for s in graph['subgraphs']:
        render(s, True)
    for e in graph['edges']:
        print '%s"%s" -> "%s";' % (prefix, e['from'], e['to'])
    print '}'

def debug(*s):
    print >>sys.stderr, s

if __name__ == '__main__':
    main()
